### ISSUE TITLE
Can't edit record in Data Center

### ISSUE THREAD

**Issue by voquoccuong** [daiduongtruong/CircleBi-Roadmap#13]
![data-center_edit_add-new-customer](https://cloud.githubusercontent.com/assets/10296099/12045457/7155b1ca-aed6-11e5-9bd3-c2e952ce6b55.jpg)

Chọn 1 dòng để edit lại Customer Name trong Data Center  --> nhập Customer mới --> rồi trỏ chuột chỗ khác --> load 30 phút vẫn không lưu được :(

**Comment by daiduongtruong** [comment]
Em đã fix bug này. Anh Cường confirm lại giúp em nhé.

**Comment by voquoccuong** [comment]
Ok, anh test thấy được rồi đó em
