### ISSUE TITLE
Data empty but Dashboard still cached?

### ISSUE THREAD

**Issue by voquoccuong** [daiduongtruong/CircleBi-Roadmap#14]
Hi Dương, 
Em xem giúp anh lỗi này.
- Data anh đã xóa hết rồi (để import lại dữ liệu chuẩn)
- Nhưng vào Dashboard thì chart vẫn hiển thị có dữ liệu
![dataempty_chartcached_error_20160102](https://cloud.githubusercontent.com/assets/10296099/12073644/50770c42-b15b-11e5-9f82-07384d028998.jpg)

**Comment by daiduongtruong** [comment]
Hi anh, là bug liên quan đến việc caching bên em. Em vừa fix rồi. Anh check lại giúp em nhé :)

**Comment by voquoccuong** [comment]
Anh đã thấy mất cache rồi đó. Cảm ơn Dương!
