### ISSUE TITLE
Bug | Add Data manual - can't select Category, Customer....

### ISSUE THREAD

**Issue by voquoccuong** [daiduongtruong/CircleBi-Roadmap#15]
Khi Add Data manual không thể chọn các loại Category, Customer... được
--> thấy hình như z-index của cái Drop-down list này bị lỗi :( (xem ảnh)
![add_data_category-cant-select](https://cloud.githubusercontent.com/assets/10296099/12078753/ae8b1656-b251-11e5-800e-b5a8ebdbd613.jpg)

**Comment by daiduongtruong** [comment]
Thank anh Cường. Em đã fix lỗi này. Anh check lại giúp em nhé.
